import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Coffee from "~/components/Coffee";

import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffi - El café que impulsa la innovación</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-blackMain to-blackLigth">
        <div className="container flex flex-col justify-center gap-12 px-4 py-16 ">
          <div>
            <span className="text-2xl text-white font-black text-center"> {"<Coff/>"}</span>
          </div>
          <div className="flex flex-col gap-8">
            <h1 className="text-7xl text-white font-black text-center">
              El café que impulsa la innovación
            </h1>
            <p className="text-grayStrong text-2xl font-semibold text-center">Impulsando la productividad y la creatividad de los ingenieros de software</p>
            <div className="flex flex-col items-center gap-2">
              <AuthShowcase />
            </div>
          </div>
          <div className="flex flex-col gap-2 w-full justify-center items-center">
            <Coffee />
          </div>
          <div className="flex flex-col gap-4">
            <p className="text-whiteMain font-bold text-4xl">Tu café como te gusta</p>
            <div className="flex flex-col gap-2">
              <div className="flex-col flex gap-1">
                <p className="text-whiteMain font-bold text-lg">Agile Americano</p>
                <p className="text-grayStrong">Suave y rápido, como tus ciclos de sprint.</p>
              </div>
              <div className="flex-col flex gap-1">
                <p className="text-whiteMain font-bold text-lg">Full-Stack Blend</p>
                <p className="text-grayStrong">Una combinación equilibrada tanto para desarrolladores de front-end como de back-end.</p>
              </div>
              <div className="flex-col flex gap-1">
                <p className="text-whiteMain font-bold text-lg">Debug Dark Roast</p>
                <p className="text-grayStrong">Un café fuerte y audaz para potenciar las sesiones de depuración.</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Únete a la Waitlist"}
      </button>
    </div>
  );
}
